### ISSUE TITLE
Premature Garbage Collection of AllocBuffer

### ISSUE THREAD

**Issue by dnkats** [MasonProtter/Bumper.jl#46]
GC sometimes deallocates the buffer, when using AllocBuffer allocator. For example, the following consistently fails with segmentation fault for me:
```
using Bumper
using Random, TensorOperations

function main()
  buf = AllocBuffer(sizeof(Float64)*(301*300*300))
  C = zeros(300,300,300)
  for i in 1:100
    @no_escape buf begin
      A = @alloc(Float64, 300, 300 ,300)
      B = @alloc(Float64, 300, 300)
      rand!(A)
      rand!(B)
      @tensor C[i,j,k] = A[i,j,m] * B[m,k]
    end
  end
end
main()
```

A possible solution would be to use `GC.@preserve buf begin ... end` in the `@no_escape` macro.

**Comment by MasonProtter** [comment]
Hm, interesting yeah. I think most of my testing of this has been assuming the buffer is captured somewhere, but you're right, in cases like this GC can collect it causing major problems.
