### ISSUE TITLE
Composing with distinct allocators

### ISSUE THREAD

**Issue by mkitti** [MasonProtter/Bumper.jl#7]
In ArrayAllocators.jl, I made some bindings for several allocations functions:

1. `posix_memalign`
2. `VirtualAlloc2`
3. `VirtualAllocEx`
4. `numa_alloc_onnode`
5. `numa_alloc_local`

What would be a good way to compose ArrayAllocators.jl and Bumper.jl?

**Comment by MasonProtter** [comment]
These packages are doing pretty different things, it doesn't seem like ArrayAllocators.jl has any *deallocation* mechanisms, and is concerned with heap style allocation, whereas Bumper.jl is essentially an alternative stack.
